#!/bin/sh

if [ $LOCAL_POOL ]; then
    cd $LOCAL_POOL
    d=`pwd`
    echo "Local pool: $d"
    grep "$d" /etc/apt/sources.list > /dev/null 2>&1

    if [ "$?" != "0" ]; then
	echo "deb file:$d ./" >> /etc/apt/sources.list
    fi

    dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
fi

apt-get update
