#!/bin/sh

BINDMOUNTS=/var/cache/pbuilder/precise-amd64/result
if [ $POOL ]; then
    cd $BINDMOUNTS
    d=`pwd`
    echo $d
    grep "$d" /etc/apt/sources.list > /dev/null 2>&1

    if [ "$?" != "0" ]; then
	echo "deb file:$d ./" >> /etc/apt/sources.list
    fi

    dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
fi

# add unity staging ppa for external dep
echo "deb http://ppa.launchpad.net/unity-team/staging/ubuntu precise main" >> /etc/apt/sources.list
apt-get update
